### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Reichenbachian** [salu133445/lakh-pianoroll-dataset#1]
The LPD-Cleansed dataset link is broken. Is there any chance I could get that link/dataset?

**Comment by JunShern** [comment]
Seconded. I managed to download the dataset some time ago but the link seems to have gone down now. Can anyone help?

**Comment by salu133445** [comment]
Hi there, I forgot to change the sharing permissions. It's now working. Let me know if any of them is down.
