### ISSUE TITLE
creating dataset with a jazz tag

### ISSUE THREAD

**Issue by VladJamir** [salu133445/lakh-pianoroll-dataset#2]
so I derived the id list for lastfm with the jazz tag using `derive_id_list_lastfm.py`, upon checking the `id_list_jazz.txt` it only contained the MSD ID, no MIDI filename, how will I do this?

**Comment by salu133445** [comment]
You can acquire the corresponding MIDI filename(s) with either `matched_ids.txt` or `cleansed_ids.txt`.
